### ISSUE TITLE
Failed to load mod entrypoint

### ISSUE THREAD

**Issue by kilex109** [Serega007RU/BetterCSC#5]
java.lang.IllegalStateException: Failed to load mod entrypoint
	at dev.xdark.clientapi.loader.Loader.load(SourceFile:202)
	at ru.cristalix.client.CristalixClient.startGame(SourceFile:255)
	at net.minecraft.client.Minecraft.handler$zzm000$onClientStarted(SourceFile:3279)
	at net.minecraft.client.Minecraft.init(SourceFile:557)
	at net.minecraft.client.Minecraft.run(SourceFile:341)
	at net.minecraft.client.main.Main.doStart(SourceFile:194)
	at net.minecraft.client.main.Main.lambda$main$3(SourceFile:185)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 67
	at org.objectweb.asm.ClassReader.<init>(SourceFile:196)
	at org.objectweb.asm.ClassReader.<init>(SourceFile:177)
	at org.objectweb.asm.ClassReader.<init>(SourceFile:163)
	at dev.xdark.clientapi.loader.ModClassLoader.loadClass0(SourceFile:110)
	at dev.xdark.clientapi.loader.ModClassLoader.findClass(SourceFile:66)
	at dev.xdark.clientapi.loader.Loader.load(SourceFile:200)
	... 8 more

**Comment by Serega007RU** [comment]
Ты разработчик мода?

**Comment by YBGRAZE** [comment]
да мы свой мод запилить хотим
выходит такой прикол

чем ты билдил?

**Comment by Serega007RU** [comment]
Надо билдить для 8-ой джавы, да, именно для 8-ой, не смотря на то что клиент кристаликса на 23-ей джаве, моды на ней загружаются только если они сбилжены для 8-ой джавы

**Comment by Serega007RU** [comment]
Да, надо вот тут сменить версию джавы
![image](https://github.com/Serega007RU/BetterCSC/assets/64780091/33d93f76-2fe0-4d70-b9b8-48054855b126)

Но возможно версию Java надо менять и в настройках самого проекта (не для всего IntelliJ), по крайней мере я менял как там где по скрину

P.S. скрин я взял из интернета, пока у меня нет возможности зайти со своего компа

**Comment by kilex109** [comment]
> Надо билдить для 8-ой джавы, да, именно для 8-ой, не смотря на то что клиент кристаликса на 23-ей джаве, моды на ней загружаются только если они сбилжены для 8-ой джавы

Спасибо большое, сработало. Я зашёл в Project Structure и сменил версию Java на 1.8.0
![image](https://github.com/Serega007RU/BetterCSC/assets/88145779/2f9b03d5-b2d7-4f6e-8904-17caf9a46d8c)
